// AUTO-GENERATED by scripts/gen-stretch-images.js. Do not edit by hand.
// Maps an image basename (slug, no extension) to its bundled require().
import type { ImageSourcePropType } from 'react-native';

export const STRETCH_IMAGES: Record<string, ImageSourcePropType> = {};
