// In-app legal content. Canonical, publishable versions live in docs/legal/*.md
// and must be kept in sync with these. Replace the placeholder contacts before
// publishing.

export const CONTACT_EMAIL = 'gentian.hoxha91@gmail.com'; // TODO: replace with a real, monitored address

export interface LegalSection {
  heading: string;
  body: string;
}

export interface LegalDoc {
  id: 'disclaimer' | 'privacy' | 'terms' | 'copyright';
  title: string;
  updated: string;
  sections: LegalSection[];
}

const UPDATED = '2026-05-30';

export const MEDICAL_DISCLAIMER: LegalDoc = {
  id: 'disclaimer',
  title: 'Medical Disclaimer',
  updated: UPDATED,
  sections: [
    {
      heading: 'Not medical advice',
      body: 'FlexAI Coach provides general fitness, stretching, mobility, and wellness information for educational purposes only. It does not diagnose, treat, cure, or prevent any condition and is not a substitute for professional medical advice, diagnosis, or treatment.',
    },
    {
      heading: 'Always seek professional advice',
      body: 'Always consult a physician, physical therapist, or qualified health provider about any pain, injury, or medical condition, and before beginning any exercise or stretching program. Never disregard or delay professional advice because of something in this app.',
    },
    {
      heading: 'Stop and seek help',
      body: 'Stop immediately and seek medical care if you feel sharp, severe, or sudden pain; numbness, tingling, or weakness; swelling or inability to move a limb; dizziness, chest pain, or shortness of breath; pain after an accident or fall; or symptoms that worsen. If you think you have a medical emergency, call your local emergency number.',
    },
    {
      heading: 'Assumption of risk',
      body: 'Physical activity carries inherent risks. By performing any suggested activity you voluntarily assume all risk of injury and are responsible for exercising within your own limits.',
    },
    {
      heading: 'AI-generated content',
      body: 'Some guidance may be generated by automated systems and can be incomplete or incorrect. Use your judgment and consult a professional when in doubt.',
    },
  ],
};

export const PRIVACY_POLICY: LegalDoc = {
  id: 'privacy',
  title: 'Privacy Policy',
  updated: UPDATED,
  sections: [
    {
      heading: 'Privacy by design',
      body: 'The app is built to collect as little data as possible. You can use core features without an account. Anything you type about pain, soreness, injuries, or body areas is treated as sensitive.',
    },
    {
      heading: 'Chat is not stored',
      body: 'Your messages and the suggestions you receive exist only in memory while the app is open. They are not saved to disk or any server and are gone when you close the app.',
    },
    {
      heading: 'What is stored on your device',
      body: 'Only a consent record (that you accepted this policy and the disclaimer, plus the date) and optional profile preferences you choose to set (such as fitness level or goals). These stay on your device and are not sent to us. We do not collect your name, email, contacts, photos, microphone, camera, or precise location. If you turn on Save chat history (off by default) in Settings, your query text is also stored locally on your device only - never transmitted - and can be cleared any time.',
    },
    {
      heading: 'Data that leaves your device',
      body: 'The app works fully offline using an on-device stretch library. Only when the on-device matcher cannot understand your request may the app send that single message’s text to Google’s Gemini API to generate a suggestion. No identifiers, profile data, or history are sent. If no AI key is configured, this never happens. We do not use ad networks and do not sell or share your information. If you create an optional account and tap Back up, your routines, history, and preferences are stored in your own private row in the app’s Supabase database (protected so only you can read it) until you delete them. Accounts are entirely optional; without one, nothing syncs.',
    },
    {
      heading: 'Your controls',
      body: 'In Settings you can Export your locally stored data as JSON, or Delete all locally stored data. Because chat is never stored, there is no chat history to export or delete.',
    },
    {
      heading: 'Data retention',
      body: 'Locally stored data remains on your device until you delete it or uninstall the app. We keep no copies.',
    },
    {
      heading: "Children's privacy",
      body: 'The app is not directed to children under 13 (or the minimum age in your region) and we do not knowingly collect their information. A parent or guardian should review this policy and provide consent where required.',
    },
  ],
};

export const TERMS_OF_USE: LegalDoc = {
  id: 'terms',
  title: 'Terms of Use',
  updated: UPDATED,
  sections: [
    {
      heading: 'Acceptance',
      body: 'By using FlexAI Coach you agree to these Terms and to the Medical Disclaimer and Privacy Policy. If you do not agree, do not use the app.',
    },
    {
      heading: 'Not medical advice',
      body: 'The app provides general fitness information only and does not provide medical advice, diagnosis, or treatment. You assume all risks of physical activity and agree to stop and seek care for any concerning symptom.',
    },
    {
      heading: 'Acceptable use',
      body: 'Do not use the app unlawfully, rely on it for emergencies, or misuse it. This version does not provide user uploads.',
    },
    {
      heading: 'Intellectual property',
      body: 'The app and its original content are owned by the developer or its licensors. You receive a limited, personal, non-transferable, revocable license for personal, non-commercial use.',
    },
    {
      heading: 'Third-party services',
      body: 'When the optional AI fallback is used, your message text is processed by Google’s Gemini API under Google’s terms and privacy policy.',
    },
    {
      heading: 'Disclaimers & liability',
      body: 'The app is provided "as is" without warranties of any kind. To the maximum extent permitted by law, the developer is not liable for any injury or damages arising from your use of the app or performance of any suggested activity.',
    },
  ],
};

export const COPYRIGHT_POLICY: LegalDoc = {
  id: 'copyright',
  title: 'Copyright Policy',
  updated: UPDATED,
  sections: [
    {
      heading: 'Our content',
      body: 'All exercise text, design, and any media in the app are either original, licensed, public domain, or generated for use within the app. App-generated media avoids logos, brand names, likenesses, and copyrighted styles. We do not copy content from YouTube, TikTok, Instagram, or paid fitness platforms.',
    },
    {
      heading: 'User content',
      body: 'This version does not allow uploads. If added later, users must own or have permission for anything they submit, and the takedown process below applies.',
    },
    {
      heading: 'Notice & takedown',
      body: `If you believe content infringes your copyright, contact ${CONTACT_EMAIL} with your contact info, identification of the work and the infringing material, a good-faith statement, a statement under penalty of perjury that you are authorized, and your signature. We review valid notices promptly.`,
    },
  ],
};

export const LEGAL_DOCS: LegalDoc[] = [MEDICAL_DISCLAIMER, PRIVACY_POLICY, TERMS_OF_USE, COPYRIGHT_POLICY];
